<a href="https://colab.research.google.com/github/oguzhanguler1/titanic_competition/blob/main/submission1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('train.csv')

In [ ]:
dataset.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [ ]:
dataset.groupby(["Sex", "Pclass"])["Survived"].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

In [ ]:
dataset.groupby("SibSp")["Survived"].mean()

SibSp
0    0.345395
1    0.535885
2    0.464286
3    0.250000
4    0.166667
5    0.000000
8    0.000000
Name: Survived, dtype: float64

In [ ]:
dataset.groupby("Parch")["Survived"].mean()

Parch
0    0.343658
1    0.550847
2    0.500000
3    0.600000
4    0.000000
5    0.200000
6    0.000000
Name: Survived, dtype: float64

In [ ]:
dataset.groupby("Fare")["Survived"].mean()

Fare
0.0000      0.066667
4.0125      0.000000
5.0000      0.000000
6.2375      0.000000
6.4375      0.000000
              ...
227.5250    0.750000
247.5208    0.500000
262.3750    1.000000
263.0000    0.500000
512.3292    1.000000
Name: Survived, Length: 248, dtype: float64

In [ ]:
dataset.groupby("Cabin")["Survived"].mean()

Cabin
A10    0.0
A14    0.0
A16    1.0
A19    0.0
A20    1.0
      ...
F33    1.0
F38    0.0
F4     1.0
G6     0.5
T      0.0
Name: Survived, Length: 147, dtype: float64

In [ ]:
dataset["Deck"] = dataset["Cabin"].str[0]
dataset["Deck"] = dataset["Deck"].fillna("Unknown")

dataset.groupby("Deck")["Survived"].agg(["mean", "count"])

             mean  count
Deck
A        0.466667     15
B        0.744681     47
C        0.593220     59
D        0.757576     33
E        0.750000     32
F        0.615385     13
G        0.500000      4
T        0.000000      1
Unknown  0.299854    687

In [ ]:
dataset.groupby("Embarked")["Survived"].mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [ ]:
dataset["HasCabin"] = dataset["Cabin"].notnull().astype(int)

In [ ]:
dataset.groupby("HasCabin")["Survived"].agg(["mean", "count"])

              mean  count
HasCabin
0         0.299854    687
1         0.666667    204

In [ ]:
dataset.groupby(["HasCabin", "Pclass"])["Survived"].agg(["mean", "count"])

                     mean  count
HasCabin Pclass
0        1       0.475000     40
         2       0.440476    168
         3       0.235908    479
1        1       0.664773    176
         2       0.812500     16
         3       0.500000     12

In [ ]:
dataset["FamilySize"] = dataset["SibSp"] + dataset["Parch"] + 1
dataset["IsAlone"] = (dataset["FamilySize"] == 1).astype(int)

In [ ]:
dataset[["SibSp", "Parch", "FamilySize", "IsAlone"]].head()

   SibSp  Parch  FamilySize  IsAlone
0      1      0           2        0
1      1      0           2        0
2      0      0           1        1
3      1      0           2        0
4      0      0           1        1

In [ ]:
dataset.groupby("Age")["Survived"].mean()

Age
0.42     1.0
0.67     1.0
0.75     1.0
0.83     1.0
0.92     1.0
        ...
70.00    0.0
70.50    0.0
71.00    0.0
74.00    0.0
80.00    1.0
Name: Survived, Length: 88, dtype: float64

In [ ]:
from sklearn.impute import SimpleImputer

age_imputer = SimpleImputer(strategy="median")

dataset[["Age"]] = age_imputer.fit_transform(dataset[["Age"]])

In [ ]:
dataset["AgeBin"] = pd.cut(
    dataset["Age"],
    bins=[0, 12, 18, 35, 60, 100],
    labels=[0, 1, 2, 3, 4]
)

dataset.groupby("AgeBin")["Survived"].agg(["mean", "count"])

/tmp/ipykernel_1665/3832594059.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dataset.groupby("AgeBin")["Survived"].agg(["mean", "count"])

            mean  count
AgeBin
0       0.579710     69
1       0.428571     70
2       0.353271    535
3       0.400000    195
4       0.227273     22

In [ ]:
features = [
    "Pclass",
    "Sex",
    "FamilySize",
    "HasCabin",
    "IsAlone",
    "AgeBin"
]

X = dataset[features]
y = dataset["Survived"]

In [ ]:
features_2 = [
    "Pclass",
    "Sex",
    "FamilySize",
    "HasCabin",
    "AgeBin"
]
X2 = dataset[features_2]
y2 = dataset["Survived"]

In [ ]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Deck             0
HasCabin         0
FamilySize       0
IsAlone          0
AgeBin           0
dtype: int64

In [ ]:
dataset.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck,HasCabin,FamilySize,IsAlone,AgeBin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Unknown,0,2,0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C,1,2,0,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Unknown,0,1,1,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C,1,2,0,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Unknown,0,1,1,2

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[["male", "female"]])

X[["Sex"]] = encoder.fit_transform(X[["Sex"]])
X2[["Sex"]] = encoder.fit_transform(X2[["Sex"]])

/tmp/ipykernel_1665/1356397656.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[["Sex"]] = encoder.fit_transform(X[["Sex"]])
/tmp/ipykernel_1665/1356397656.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X2[["Sex"]] = encoder.fit_transform(X2[["Sex"]])

In [ ]:
X.head(5)

   Pclass  Sex  FamilySize  HasCabin  IsAlone AgeBin
0       3  0.0           2         0        0      2
1       1  1.0           2         1        0      3
2       3  1.0           1         0        1      2
3       1  1.0           2         1        0      2
4       3  0.0           1         0        1      2

In [ ]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_val)

print("Accuracy:", accuracy_score(y_val, y_pred))
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

Accuracy: 0.7877094972067039
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       110
           1       0.77      0.64      0.70        69

    accuracy                           0.79       179
   macro avg       0.78      0.76      0.77       179
weighted avg       0.79      0.79      0.78       179

[[97 13]
 [25 44]]

In [ ]:
import pandas as pd

importances = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
}).sort_values(by="Importance", ascending=False)

importances

      Feature  Importance
1         Sex    0.449104
0      Pclass    0.151358
5      AgeBin    0.135518
2  FamilySize    0.134640
3    HasCabin    0.106672
4     IsAlone    0.022708

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train, y_train)

log_pred = log_model.predict(X_val)

print("Logistic Regression Accuracy:", accuracy_score(y_val, log_pred))
print(classification_report(y_val, log_pred))
print(confusion_matrix(y_val, log_pred))

Logistic Regression Accuracy: 0.8044692737430168
              precision    recall  f1-score   support

           0       0.84      0.85      0.84       110
           1       0.75      0.74      0.74        69

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

[[93 17]
 [18 51]]

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_val)

print("Decision Tree Accuracy:", accuracy_score(y_val, dt_pred))
print(classification_report(y_val, dt_pred))
print(confusion_matrix(y_val, dt_pred))

Decision Tree Accuracy: 0.7932960893854749
              precision    recall  f1-score   support

           0       0.79      0.91      0.84       110
           1       0.81      0.61      0.69        69

    accuracy                           0.79       179
   macro avg       0.80      0.76      0.77       179
weighted avg       0.80      0.79      0.79       179

[[100  10]
 [ 27  42]]

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

gb_model = GradientBoostingClassifier(random_state=42)

gb_model.fit(X_train, y_train)

gb_pred = gb_model.predict(X_val)

print("Gradient Boosting Accuracy:", accuracy_score(y_val, gb_pred))
print(classification_report(y_val, gb_pred))
print(confusion_matrix(y_val, gb_pred))

Gradient Boosting Accuracy: 0.7932960893854749
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       110
           1       0.78      0.65      0.71        69

    accuracy                           0.79       179
   macro avg       0.79      0.77      0.77       179
weighted avg       0.79      0.79      0.79       179

[[97 13]
 [24 45]]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

knn_pred = knn_model.predict(X_val)

print("KNN Accuracy:", accuracy_score(y_val, knn_pred))
print(classification_report(y_val, knn_pred))
print(confusion_matrix(y_val, knn_pred))

KNN Accuracy: 0.7430167597765364
              precision    recall  f1-score   support

           0       0.77      0.84      0.80       110
           1       0.69      0.59      0.64        69

    accuracy                           0.74       179
   macro avg       0.73      0.72      0.72       179
weighted avg       0.74      0.74      0.74       179

[[92 18]
 [28 41]]

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

svc_model = SVC()

svc_model.fit(X_train, y_train)

svc_pred = svc_model.predict(X_val)

print("SVC Accuracy:", accuracy_score(y_val, svc_pred))
print(classification_report(y_val, svc_pred))
print(confusion_matrix(y_val, svc_pred))

SVC Accuracy: 0.8324022346368715
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       110
           1       0.82      0.72      0.77        69

    accuracy                           0.83       179
   macro avg       0.83      0.81      0.82       179
weighted avg       0.83      0.83      0.83       179

[[99 11]
 [19 50]]

In [ ]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

svm_rbf_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(kernel="rbf", random_state=42))
])

svm_rbf_model.fit(X_train, y_train)

svm_rbf_pred = svm_rbf_model.predict(X_val)

print("Kernel SVM - RBF Accuracy:", accuracy_score(y_val, svm_rbf_pred))
print(classification_report(y_val, svm_rbf_pred))
print(confusion_matrix(y_val, svm_rbf_pred))

Kernel SVM - RBF Accuracy: 0.8268156424581006
              precision    recall  f1-score   support

           0       0.81      0.95      0.87       110
           1       0.88      0.64      0.74        69

    accuracy                           0.83       179
   macro avg       0.84      0.79      0.80       179
weighted avg       0.83      0.83      0.82       179

[[104   6]
 [ 25  44]]

In [ ]:
svm_linear_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(kernel="linear", random_state=42))
])

svm_linear_model.fit(X_train, y_train)

svm_linear_pred = svm_linear_model.predict(X_val)

print("Kernel SVM - Linear Accuracy:", accuracy_score(y_val, svm_linear_pred))
print(classification_report(y_val, svm_linear_pred))
print(confusion_matrix(y_val, svm_linear_pred))

Kernel SVM - Linear Accuracy: 0.7877094972067039
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       110
           1       0.76      0.65      0.70        69

    accuracy                           0.79       179
   macro avg       0.78      0.76      0.77       179
weighted avg       0.79      0.79      0.78       179

[[96 14]
 [24 45]]

In [ ]:
svm_poly_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(kernel="poly", degree=3, random_state=42))
])

svm_poly_model.fit(X_train, y_train)

svm_poly_pred = svm_poly_model.predict(X_val)

print("Kernel SVM - Polynomial Accuracy:", accuracy_score(y_val, svm_poly_pred))
print(classification_report(y_val, svm_poly_pred))
print(confusion_matrix(y_val, svm_poly_pred))

Kernel SVM - Polynomial Accuracy: 0.8324022346368715
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       110
           1       0.82      0.72      0.77        69

    accuracy                           0.83       179
   macro avg       0.83      0.81      0.82       179
weighted avg       0.83      0.83      0.83       179

[[99 11]
 [19 50]]

In [ ]:
svm_sigmoid_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(kernel="sigmoid", random_state=42))
])

svm_sigmoid_model.fit(X_train, y_train)

svm_sigmoid_pred = svm_sigmoid_model.predict(X_val)

print("Kernel SVM - Sigmoid Accuracy:", accuracy_score(y_val, svm_sigmoid_pred))
print(classification_report(y_val, svm_sigmoid_pred))
print(confusion_matrix(y_val, svm_sigmoid_pred))

Kernel SVM - Sigmoid Accuracy: 0.6480446927374302
              precision    recall  f1-score   support

           0       0.72      0.69      0.71       110
           1       0.54      0.58      0.56        69

    accuracy                           0.65       179
   macro avg       0.63      0.64      0.63       179
weighted avg       0.65      0.65      0.65       179

[[76 34]
 [29 40]]

In [ ]:
from sklearn.svm import SVC

final_model = SVC()
final_model.fit(X_train, y_train)

final_pred = final_model.predict(X_val)

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

final_model = SVC()

final_model.fit(X_train, y_train)

final_pred = final_model.predict(X_val)

print("Final SVC Accuracy:", accuracy_score(y_val, final_pred))
print(classification_report(y_val, final_pred))
print(confusion_matrix(y_val, final_pred))

Final SVC Accuracy: 0.8324022346368715
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       110
           1       0.82      0.72      0.77        69

    accuracy                           0.83       179
   macro avg       0.83      0.81      0.82       179
weighted avg       0.83      0.83      0.83       179

[[99 11]
 [19 50]]

In [ ]:
X[features].head(5)

   Pclass  Sex AgeBin  FamilySize  HasCabin  IsAlone
0       3  0.0      2           2         0        0
1       1  1.0      3           2         1        0
2       3  1.0      2           1         0        1
3       1  1.0      2           2         1        0
4       3  0.0      2           1         0        1

In [ ]:
X_final = X
y_final = dataset["Survived"]

final_model = SVC()
final_model.fit(X_final, y_final)

SVC()

In [ ]:
# Read test data
test_dataset = pd.read_csv("test.csv")

# Sex encoding
test_dataset["Sex"] = test_dataset["Sex"].map({
    "male": 0,
    "female": 1
})

# Age imputation
age_imputer = SimpleImputer(strategy="median")
test_dataset[["Age"]] = age_imputer.fit_transform(test_dataset[["Age"]])

# AgeBin
test_dataset["AgeBin"] = pd.cut(
    test_dataset["Age"],
    bins=[0, 12, 18, 35, 60, 100],
    labels=[0, 1, 2, 3, 4],
    include_lowest=True
).astype(int)

# Family features
test_dataset["FamilySize"] = test_dataset["SibSp"] + test_dataset["Parch"] + 1
test_dataset["IsAlone"] = (test_dataset["FamilySize"] == 1).astype(int)

# Cabin feature
test_dataset["HasCabin"] = test_dataset["Cabin"].notnull().astype(int)

# Test feature matrix
X_test2 = test_dataset[X.columns]

In [ ]:
print(X_final.columns)
print(X_test2.columns)

Index(['Pclass', 'Sex', 'FamilySize', 'HasCabin', 'IsAlone', 'AgeBin'], dtype='object')
Index(['Pclass', 'Sex', 'FamilySize', 'HasCabin', 'IsAlone', 'AgeBin'], dtype='object')

In [ ]:
# Predict test data
test_predictions = final_model.predict(X_test2)

# Create submission file
submission = pd.DataFrame({
    "PassengerId": test_dataset["PassengerId"],
    "Survived": test_predictions
})

submission.to_csv("submission.csv", index=False)

submission.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1